### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by Ellcz** [dank/node-csgorc#10]
I think it try to open sentry file which is not there after first login? 

fs.js:638
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\ADMIN\Desktop\node-csgorc-master\sentry\rastad'
    at Object.fs.openSync (fs.js:638:18)
    at Object.fs.writeFileSync (fs.js:1287:33)
    at SteamUser.user.on (C:\Users\ADMIN\Desktop\node-csgorc-master\app.js:89:10)
    at emitTwo (events.js:125:13)
    at SteamUser.emit (events.js:213:7)
    at SteamUser.handlers.(anonymous function) (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\steam\lib\handlers\user\index.js:61:8)
    at SteamUser.<anonymous> (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\steam\lib\handlers\user\index.js:12:28)
    at emitThree (events.js:140:20)
    at SteamClient.emit (events.js:216:7)
    at SteamClient._netMsgReceived (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\steam\lib\steam_client.js:172:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! report@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the report@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ADMIN\AppData\Roaming\npm-cache\_logs\2017-06-03T16_15_11_823Z-debug.log

**Comment by ghost** [comment]
This script doesn't create the sentries at the first start. You need to use another library to create them. After that you can move those files, named after their account, into ProgramPath/sentry/ and it should work :)

**Comment by Ellcz** [comment]
Great! I thought it's exactly this. Let me try it. Not sure where I get sentry file tho. Maybe my booster have it. And I'll close it if it works. :)

**Comment by Ellcz** [comment]
Ok new error xD Seems like node love me again. //

C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:1817
                throw Error("Illegal value for "+self.toString(true)+" of type "+self.type.name+": "+val+" ("+msg+")");
                ^

Error: Illegal value for matchIdvalue element of type uint64: string (empty string)
    at fail (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:1817:23)
    at Element.ProtoBuf.Reflect.ElementPrototype.verifyValue (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:1857:29)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:3499:33)
    at MessagePrototype.set (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:2493:59)    at MessagePrototype.set (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:2483:38)    at Message (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:2411:34)
    at report (C:\Users\ADMIN\Desktop\node-csgorc-master\app.js:138:6)
    at SteamGameCoordinator.gc.on (C:\Users\ADMIN\Desktop\node-csgorc-master\app.js:103:13)
    at emitThree (events.js:135:13)
    at SteamGameCoordinator.emit (events.js:216:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! report@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the report@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ADMIN\AppData\Roaming\npm-cache\_logs\2017-06-03T16_40_12_879Z-debug.log

**Comment by ghost** [comment]
Can you try these commands?
`npm cache clean -f`
`npm install -g n`
`n stable`
After that you can try it again.

**Comment by ghost** [comment]
And by the way: Did you do an `npm run update` before starting it?

**Comment by Ellcz** [comment]
Yep. I tried them already few times just in case. Still same: 

 Reporting...
C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:1817
                throw Error("Illegal value for "+self.toString(true)+" of type "+self.type.name+": "+val+" ("+msg+")");
                ^

Error: Illegal value for matchIdvalue element of type uint64: string (empty string)
    at fail (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:1817:23)
    at Element.ProtoBuf.Reflect.ElementPrototype.verifyValue (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:1857:29)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:3499:33)
    at MessagePrototype.set (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:2493:59)    at MessagePrototype.set (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:2483:38)    at Message (C:\Users\ADMIN\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:2411:34)
    at report (C:\Users\ADMIN\Desktop\node-csgorc-master\app.js:138:6)
    at SteamGameCoordinator.gc.on (C:\Users\ADMIN\Desktop\node-csgorc-master\app.js:103:13)
    at emitThree (events.js:135:13)
    at SteamGameCoordinator.emit (events.js:216:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! report@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the report@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ADMIN\AppData\Roaming\npm-cache\_logs\2017-06-03T16_50_49_833Z-debug.log

Seems like reportbot really want MATCHID.. But why? We need to bot them in game, not after game with matchID. MatchID can be (and used to be) blank. I never needed it.

Yes updated. :) Of course. I checked for every solution so far. This is actually third error. The error before was fixed by me. I deleted it after I realised what's wrong. But here I'm lost.

**Comment by ghost** [comment]
What are you trying to pass at matchid? You need to pass the number value not the "CSGO-xxxxx". 
You can use http://noteefy.de/cs/tools/sharecode.php?code=CSGO-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx to get the result.
EDIT: Okay, I see what you wanted to do. Let me explain something: Valve changed the way how reports are getting accepted to prevent report bots with spoofed accounts. You NEED to pass the MatchID now, otherwise you're not getting an answer from the GC. It does make sense though because they get overwatched on this exact match ;)

**Comment by dank** [comment]
>Error: Illegal value for matchIdvalue element of type uint64: string (empty string)

To piggyback from @NoTeefy, you need an uint64 value or I THINK (I hope) you can just leave it blank.

**Comment by Ellcz** [comment]
Exactly, that's what I did. For example zoner does not need matchID. Because the game is live. You can get matchID only after the game. After that reportbot should not even work.

When this reportbot ask me for MatchID, I simply leave it blank.

**Comment by ghost** [comment]
I don't know how the reports from zoner are passing through then since I've tested it and I only got accepted reports after that match was done.

**Comment by dank** [comment]
AFAIK, for report bot to work you need the match id. Don't quote me on this however.

You can use this offset to grab it. 
> "client.dll", "55 8B EC A1 ? ? ? ? 83 EC 08 D1 E8");

**Comment by Ellcz** [comment]
It should be like 15 minutes after game ended to still get the reports, right? Also you should check for original reportbot which sadly does not work with SteamGuard acc's. He don't need MatchID and reportbot still works. Sadly I really want to use this one because of SteamGuard.

**Comment by dank** [comment]
Ah, thanks for the clarification. I didn't know. You should be able to leave MatchID blank and not cause this issue. I believe it's something else. Do you mind clearing your /sentry/ folder and trying again from the beginning?

**Comment by ghost** [comment]
It doesn't work, trust me. You get the standard "successfully reported with confirmation id xxx" but they get nulled on the serverside. As I've stated this has to do with how Valve patched the old method with spoofed accounts and blank matchids.
I have to admit that Dank's right with his statement, it shouldn't throw an error if you pass nothing.

**Comment by Ellcz** [comment]
Of course. :) I even redownloaded the script.

// You can trust me, also. Me and my friends botted guy normally without MatchID like 3 weeks ago. And Valve definitely fixed reportbots (spoofed reports) months ago. So this is not the issue. I know Valve said it is "nulled serverside" but "program will say report passed thru" but they literally lie about everything.

**Comment by dank** [comment]
I think I found a way to reproduce your bug. I'm working on a fix right now.

**Comment by ghost** [comment]
After a little examination your error makes sense. I pushed a pull request for Dank.
And thanks for the clarification, I didn't notice that there was still a way to get them through without matchIds (I checked that some months ago).

**Comment by Ellcz** [comment]
Ok Thank You. :) By the way. After talking with you guys about this I think it will be good if I actually try buy some more accs with multiple reportbots to actually show definite proof that you don't really need matchID.

As far as I know, Valve patch is only simple check if the account you are reportbotting with is banned account. (OW / VAC ban). This report will not work. But with proper steam acc with CS:GO everything should work. It must work. I doubt they really fixed something else.

Just don't close this yet. I'm gonna post some proof ASAP.

// Oh. Ok. But I'm still gonna try it. I even need to check something else. ;3 Btw nice fix. I had same idea. xD

**Comment by ghost** [comment]
Great! Looking forward to it, I can assist you with 28 accounts. Gonna test it next week.

**Comment by dank** [comment]
If you pull master again, your bug should be fixed! Let us know.

**Comment by Ellcz** [comment]
I'm clueless. This happens to me a lot. When I or someone fixes one error, second one appear. 

C:\Users\ADMIN\Desktop\reportbot\app.js:67
          }, new Protos.CMsgClientHello({}).toBuffer());
             ^

TypeError: Protos.CMsgClientHello is not a constructor

I tried update, redownload, cleaning... etc.. Still same. Have few others ideas but give me some time.

**Comment by ghost** [comment]
Strange, it's working on my side. What's the content of your app.js on line 67?
it should be `          }, new Protos.CMsgClientHello({}).toBuffer());`

**Comment by Ellcz** [comment]
Yep. That's alright. I have the same. :D I'm always so unlucky. Not sure why.

**Comment by ghost** [comment]
Do you have a helpers folder in your path? (ProgramPath/helpers)
If not try running `npm run update` where your app.js is placed.

**Comment by Ellcz** [comment]
Yes I have. :) I update it like everytime just to be sure.

**Comment by cyborg-nation** [comment]
getting same error, btw using the sentry files of vap0r reportbot doesn't seem to work at all.

vap0r reportbot has the same update file as you but it doesn't seem like i can get any hit nowadays with it weird. Are you sure everything is still working?

**Comment by ghost** [comment]
@Ellcz 
Just a little update on the topic which reporting method works and which doesn't:
Reporting after a match has ended (and within 3 days) will work and put the hacker into the overwatch queue for this specific game, reporting without matchids however doesn't put them into the OW queue for the current game they are in (had 2 ragers and they weren't put into OW even though I reported them without matchids during the half-time).
As for the conclusion: Both methods work, but if you're reporting without matchids their next match is getting analyzed in which they can toggle off and avoid getting banned.
