### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by maplinx** [dank/node-csgorc#13]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle report@1.0.0~prestart: report@1.0.0
6 silly lifecycle report@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle report@1.0.0~start: report@1.0.0
8 verbose lifecycle report@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle report@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Program Files\Git\node-csgorc\node_modules\.bin;C:\Program Files\Git\cmd;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Owner\AppData\Local\Microsoft\WindowsApps;C:\Users\Owner\AppData\Roaming\npm
10 verbose lifecycle report@1.0.0~start: CWD: C:\Program Files\Git\node-csgorc
11 silly lifecycle report@1.0.0~start: Args: [ '/d /s /c', 'node app.js' ]
12 silly lifecycle report@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle report@1.0.0~start: Failed to exec start script
14 verbose stack Error: report@1.0.0 start: `node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid report@1.0.0
16 verbose cwd C:\Program Files\Git\node-csgorc
17 verbose Windows_NT 10.0.15063
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 verbose node v8.1.2
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error report@1.0.0 start: `node app.js`
23 error Exit status 1
24 error Failed at the report@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by maplinx** [comment]
C:\Program Files\Git\node-csgorc\app.js:67
          }, new Protos.CMsgClientHello({}).toBuffer());
             ^

TypeError: Protos.CMsgClientHello is not a constructor
    at Timeout.setInterval [as _onTimeout] (C:\Program Files\Git\node-csgorc\app.js:67:14)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! report@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the report@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2017-06-26T06_19_39_450Z-debug.log

**Comment by maplinx** [comment]
C:\Program Files\Git\node-csgorc>npm install
npm WARN report@1.0.0 No repository field.
