### ISSUE TITLE
stuck at logging in...

### ISSUE THREAD

**Issue by emreires** [dank/node-csgorc#19]
Every account is stucking logging in...

**Comment by duxeyo** [comment]
i will release my own version of this, just give me some time
im almost done with it

**Comment by emreires** [comment]
Thanks :)

**Comment by emreires** [comment]
Didnt finish 😄 ?

**Comment by idontneedhelp** [comment]
Update Protos links and update server.js in node_modules/steam/lib/
No need for a useless new script. This one works fine.

**Comment by emreires** [comment]
```
C:\Users\USER\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:784
                throw e;
                ^

Error: Parse error at line 1: unexpected '404'
    at Parser.ProtoBuf.DotProto.ParserPrototype.parse (C:\Users\USER\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:779:35)
    at Function.ProtoBuf.DotProto.Parser.parse (C:\Users\USER\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:797:39)
    at Object.ProtoBuf.loadProto (C:\Users\USER\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:5128:59)
    at Object.ProtoBuf.loadProtoFile (C:\Users\USER\Desktop\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:5174:52)
    at Object.<anonymous> (C:\Users\USER\Desktop\node-csgorc-master\helpers\protos.js:6:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

```

**Comment by idontneedhelp** [comment]
Update ur  PROTOSLINK

**Comment by idontneedhelp** [comment]
Replace this as ur updater.js:
https://ufile.io/u1z5b
