### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Waller1337** [dank/node-csgorc#20]
Error: Parse error at line 1: unexpected '404'
    at Parser.ProtoBuf.DotProto.ParserPrototype.parse (C:\Users\YOGU\Downloads\node-csgorc-master\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:779:35)
    at Function.ProtoBuf.DotProto.Parser.parse (C:\Users\YOGU\Downloads\node-csgorc-master\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:797:39)
    at Object.ProtoBuf.loadProto (C:\Users\YOGO\Downloads\node-csgorc-master\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:5128:59)
    at Object.ProtoBuf.loadProtoFile (C:\Users\YOGO\Downloads\node-csgorc-master\node-csgorc-master\node_modules\protobufjs\dist\protobuf.js:5174:52)
    at Object.<anonymous> (C:\Users\YOGO\Downloads\node-csgorc-master\node-csgorc-master\helpers\protos.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by Jaeger33211** [comment]
Get your Protos manually

**Comment by rdelian** [comment]
So what exactly I have to do because I get the same error


```
root@vmi271640:~/workspace/csgo/node-csgorc# npm start

> report@1.0.0 start /root/workspace/csgo/node-csgorc
> node app.js

/root/workspace/csgo/node-csgorc/node_modules/protobufjs/dist/protobuf.js:784
                throw e;
                ^

Error: Parse error at line 1: unexpected '404'
    at Parser.ProtoBuf.DotProto.ParserPrototype.parse (/root/workspace/csgo/node-csgorc/node_modules/protobufjs/dist/protobuf.js:779:35)
    at Function.ProtoBuf.DotProto.Parser.parse (/root/workspace/csgo/node-csgorc/node_modules/protobufjs/dist/protobuf.js:797:39)
    at Object.ProtoBuf.loadProto (/root/workspace/csgo/node-csgorc/node_modules/protobufjs/dist/protobuf.js:5128:59)
    at Object.ProtoBuf.loadProtoFile (/root/workspace/csgo/node-csgorc/node_modules/protobufjs/dist/protobuf.js:5174:52)
    at Object.<anonymous> (/root/workspace/csgo/node-csgorc/helpers/protos.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! report@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the report@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-09T22_12_46_933Z-debug.log


```
